spring:
  application:
    name: FileShareApp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/secure_file_db?ssl=require
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG