server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: FileShareApp
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    protocol: ${MAIL_PROTOCOL}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    ssl:
      enabled: false
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jta:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
#          provider:
#
#              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#              token-uri: https://oauth2.googleapis.com/token
#              user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
#              user-name-attribute: sub

