spring:
  application:
    name: FileShareApp
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/secure_file_db?ssl=require
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    protocol: ${MAIL_PROTOCOL}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    ssl:
      enabled: false
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory


server:
  servlet:
    context-path: /api

logging:
  file:
    name: logs/app.logs
  level:
    com:
      secure: INFO
    org:
      springframework:
        security: DEBUG
    root: INFO
