services:

  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      - 'POSTGRES_DB=file_share'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure_file_share_network

volumes:
  postgres_data:

networks:
  secure_file_share_network:
    driver: bridge
