package com.secure.FileShareApp.entity;

public enum AuditAction {
    UPLOAD_FILE,
    DELETE_FILE,
    DOWNLOAD_FILE,
    SHARE_FILE,
    RENAME_FILE,
    UPDATE_PERMISSIONS,
    VIEW_FILE,
    VIEW_AUDIT_LOG,
    EDIT_FILE,
    FOLDER_ACTION,
    GRANT_ACCESS,
    REVOKE_ACCESS,

    CREATE_USER,
    DELETE_USER,
    UPDATE_USER,
    MAKE_ADMIN,
    REVOKE_ADMIN,

    USER_LOGIN,
    USER_LOGOUT,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,

    SYSTEM_ERROR,
    UNKNOWN_ACTION,

    VIEW_FILE_ACCESS_LIST,
    VIEW_FILE_PERMISSION,
    VIEW_USER,
    VIEW_USERS_BY_ROLE
}
